### PR TITLE
Incorporated Privacy API

### PR DESCRIPTION
**Pull request by Anupamatd**
Hi,

We have added privacy API changes as it is required since Moodle 3.5.

Please find the below Issue tracker.
https://tracker.moodle.org/browse/CONTRIB-7345

Thanks,
Anupama

### CODE REVIEW

**Comment by azrek** [comment]
hi @gbateson 

Can you please let us know when you'll be reviewing this pull request? Do you require anything else for it?

Cheers!

**Comment by gbateson** [comment]
Thanks very much Anupamatd and Azrek.

The privacy files have been added to the public release of the HotPot module for Moodle, which is now available from [Github.com](https://github.com/gbateson/moodle-mod_hotpot) and [Moodle.org](https://moodle.org/plugins/view.php?plugin=mod_hotpot)

Best regards
Gordon

**Comment by azrek** [comment]
Thanks for merging @gbateson  !

Cheers.

**Comment by danmarsden** [comment]
Thanks Gordon! :-)

**Comment by Anupamatd** [comment]
Thanks Gordon :)

**Comment by danmarsden** [comment]
@gbateson - I've just had a look and I see that @Anupamatd has not uused the privacy api "polyfill" in this pull request, which means that it might fail/cause some problems for 3.3 and 3.4 sites - you might need to release this as only for 3.5 and higher or we might need to look at adding the polyfill to support 3.3 and 3.4 sites.

**Comment by gbateson** [comment]
Ah, yes. Well spotted Dan.
I think I know how to do that.
I will add it and recommit.

**Pull request merged**
